# Generated by Django 5.0.4 on 2024-05-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='continent',
            options={'verbose_name': 'Континент', 'verbose_name_plural': 'Континенты'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='form',
            options={'verbose_name': 'Форма правления', 'verbose_name_plural': 'Формы правления'},
        ),
        migrations.AddField(
            model_name='country',
            name='c_code',
            field=models.CharField(default='none', max_length=100, verbose_name='Код страны'),
        ),
    ]
